services:
  # Service 1: App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db-02-container
    env_file:
      - .env
    ports:
      - "${APP_PORT}:80"
    networks:
      - app-network

  # Service 2: PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: db-02-postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Service 4: adminer
  adminer:
    image: adminer
    container_name: db-02-adminer
    env_file:
      - .env
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - app-network
    depends_on:
      - postgres

# Volumes
volumes:
  postgres-data:

    # Networks
networks:
  app-network:
    driver: bridge
